<?php

declare(strict_types=1);

use App\Application\Actions\Auth\GoogleCallbackAction;
use App\Application\Actions\Auth\GoogleStartAction;
use App\Application\Actions\Auth\LoginAction;
use App\Application\Actions\Auth\LogoutAction;
use App\Application\Actions\Auth\RegisterAction;
use App\Application\Actions\BacBottles\ArchiveBacBottleAction;
use App\Application\Actions\BacBottles\BurnBacBottleAction;
use App\Application\Actions\BacBottles\CreateBacBottleAction;
use App\Application\Actions\BacBottles\CurrentBacBottleAction;
use App\Application\Actions\BacBottles\DeleteBacBottleAction;
use App\Application\Actions\BacBottles\ListBacBottlesAction;
use App\Application\Actions\BacBottles\PatchBacBottleAction;
use App\Application\Actions\BacBottles\ViewBacBottleAction;
use App\Application\Actions\Catalog\CreatePeptideTypeAction;
use App\Application\Actions\Catalog\ListPeptideTypesAction;
use App\Application\Actions\Compounds\AdjustCompoundAction;
use App\Application\Actions\Compounds\ArchiveCompoundAction;
use App\Application\Actions\Compounds\CreateCompoundAction;
use App\Application\Actions\Compounds\CurrentCompoundAction;
use App\Application\Actions\Compounds\DeleteCompoundAction;
use App\Application\Actions\Compounds\ListCompoundsAction;
use App\Application\Actions\Compounds\ListOpenCompoundsAction;
use App\Application\Actions\Compounds\PatchCompoundAction;
use App\Application\Actions\Compounds\ViewCompoundAction;
use App\Application\Actions\Health\HealthAction;
use App\Application\Actions\Me\ExportUserAction;
use App\Application\Actions\Me\SetPasswordAction;
use App\Application\Actions\Me\ViewMeAction;
use App\Application\Actions\Syringes\BurnSyringeAction;
use App\Application\Actions\Syringes\CreateSyringeAction;
use App\Application\Actions\Syringes\DeleteSyringeAction;
use App\Application\Actions\Syringes\ListSyringesAction;
use App\Application\Actions\Syringes\PatchSyringeAction;
use App\Application\Actions\Syringes\RestockSyringeAction;
use App\Application\Actions\Syringes\ViewSyringeAction;
use App\Application\Actions\Uses\CreateUseAction;
use App\Application\Actions\Uses\DeleteUseAction;
use App\Application\Actions\Uses\ListUsesAction;
use App\Application\Actions\Uses\PatchUseAction;
use App\Application\Actions\Uses\ViewUseAction;
use App\Application\Middleware\SessionAuthMiddleware;
use Slim\App;
use Slim\Interfaces\RouteCollectorProxyInterface as Group;

return function (App $app): void {
    $app->group('/api/v1', function (Group $group): void {
        $group->get('/health', HealthAction::class);
        $group->post('/auth/register', RegisterAction::class);
        $group->post('/auth/login', LoginAction::class);
        $group->post('/auth/logout', LogoutAction::class);
        $group->get('/auth/google/start', GoogleStartAction::class);
        $group->get('/auth/google/callback', GoogleCallbackAction::class);

        $group->group('', function (Group $authed): void {
            $authed->get('/me', ViewMeAction::class);
            $authed->post('/me/password', SetPasswordAction::class);
            $authed->get('/me/export', ExportUserAction::class);
            $authed->get('/peptide-types', ListPeptideTypesAction::class);
            $authed->post('/peptide-types', CreatePeptideTypeAction::class);
            $authed->get('/syringes', ListSyringesAction::class);
            $authed->post('/syringes', CreateSyringeAction::class);
            $authed->get('/syringes/{id}', ViewSyringeAction::class);
            $authed->patch('/syringes/{id}', PatchSyringeAction::class);
            $authed->delete('/syringes/{id}', DeleteSyringeAction::class);
            $authed->post('/syringes/{id}/restock', RestockSyringeAction::class);
            $authed->post('/syringes/{id}/burn', BurnSyringeAction::class);
            $authed->get('/bac-bottles', ListBacBottlesAction::class);
            $authed->post('/bac-bottles', CreateBacBottleAction::class);
            $authed->get('/bac-bottles/current', CurrentBacBottleAction::class);
            $authed->get('/bac-bottles/{id}', ViewBacBottleAction::class);
            $authed->patch('/bac-bottles/{id}', PatchBacBottleAction::class);
            $authed->delete('/bac-bottles/{id}', DeleteBacBottleAction::class);
            $authed->post('/bac-bottles/{id}/burn', BurnBacBottleAction::class);
            $authed->post('/bac-bottles/{id}/archive', ArchiveBacBottleAction::class);
            $authed->get('/compounds', ListCompoundsAction::class);
            $authed->post('/compounds', CreateCompoundAction::class);
            $authed->get('/compounds/open', ListOpenCompoundsAction::class);
            $authed->get('/compounds/current', CurrentCompoundAction::class);
            $authed->get('/compounds/{id}', ViewCompoundAction::class);
            $authed->patch('/compounds/{id}', PatchCompoundAction::class);
            $authed->delete('/compounds/{id}', DeleteCompoundAction::class);
            $authed->post('/compounds/{id}/adjust', AdjustCompoundAction::class);
            $authed->post('/compounds/{id}/archive', ArchiveCompoundAction::class);
            $authed->get('/uses', ListUsesAction::class);
            $authed->post('/uses', CreateUseAction::class);
            $authed->get('/uses/{id}', ViewUseAction::class);
            $authed->patch('/uses/{id}', PatchUseAction::class);
            $authed->delete('/uses/{id}', DeleteUseAction::class);
        })->add(SessionAuthMiddleware::class);
    });
};
